use super::data_structure::exceed_bound;
use super::rollout::{get_trace, rollout};
use super::search::{Parameters, Search, Solution};
use super::util::{print_primal_bound, TimeKeeper};
use dypdl::{variable_type::Numeric, Model, ParentAndChildStateFunctionCache, State, Transition};
use rand::prelude::*;
use rand_pcg::Pcg64Mcg;
use std::error::Error;
use std::fmt::{Debug, Display};
use std::rc::Rc;
use std::str;

/// How a neighbor is accepted or rejected.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum LocalSearchMode {
    // Accept a neighbor if better than current best
    HillClimbing,
    // accept bad solutions with a probability that decreases as the temperature cools down
    SimulatedAnnealing {
        T0: f64,
        alpha: f64,
    },
}

/// Which neighbourhoods are used during this local search. At least one should be used.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Neighborhoods {
    pub swap: bool,
    pub relocate: bool,
    pub replace: bool,
    pub twoopt: bool,
}

// Which neighborhood kind a single call to `generate_neighbor` produced.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum NeighborhoodKind {
    Swap,
    Relocate,
    Replace,
    TwoOpt,
}

//default is use both
impl Default for Neighborhoods {
    fn default() -> Neighborhoods {
        Neighborhoods {
            swap: true,
            relocate: true,
            replace:true,
            twoopt: true
        }
    }
}

/// Parameters for [`LocalSearch`].
#[derive(Debug, Clone, Copy)]
pub struct LocalSearchParameters<T> {
    /// Random seed.
    pub seed: u64,
    /// hill climbing or simulated annealing
    pub mode: LocalSearchMode,
    /// Which neighborhoods to try.
    pub neighborhoods: Neighborhoods,
    pub parameters: Parameters<T>, //time limit and quiet
}

pub struct LocalSearch<T: Numeric, B> {
    model: Rc<Model>,
    base_cost_evaluator: B,
    root_cost: T,
    current: Vec<Transition>,
    current_cost: T, // cost type is generic (can be int, can be float)
    // Cache of the state/cost after each prefix of current
    current_states: Vec<State>,
    current_costs: Vec<T>,
    // Best solution found so far, we return it 
    best: Solution<T>,
    // Whether the first solution found by CABS is feasible and has at least 2 transitions
    solvable: bool,
    mode: LocalSearchMode,
    neighborhoods: Neighborhoods,
    temperature: f64,
    rng: Pcg64Mcg, // random number generator
    time_keeper: TimeKeeper,
    quiet: bool, //do we print log/debugs output
    first_call: bool,
    candidate_transitions: Vec<Transition>, // candidate solution generated by the neighborhood exploration
}

impl<T, B> LocalSearch<T, B>
where
    T: Numeric + Ord + Display,
    <T as str::FromStr>::Err: Debug,
    B: FnMut(T, T) -> T,
{
    /// Creates a new local search starting from `transitions`.
    pub fn new(
        model: Rc<Model>,
        transitions: Vec<Transition>, //initial solution
        cost: Option<T>, //cost of the initial solution, or None if infeasible
        initial_time: f64, //elapsed time already spent finding the initial solution (e.g. by CABS)
        root_cost: T, //base cost for rollout from the root state
        base_cost_evaluator: B, //how to combined accumulated cost
        // with cost when reaching a base state 
        parameters: LocalSearchParameters<T>,
    ) -> LocalSearch<T, B> {
        assert!(
            parameters.neighborhoods.swap || parameters.neighborhoods.relocate || parameters.neighborhoods.replace || parameters.neighborhoods.twoopt,
            "at least one neighborhood (swap, relocate, replace, or twoopt) must be enabled"
        );
        // solvable is true if we start from a valid cabs solution with at least 2 transitions
        let solvable = cost.is_some() && transitions.len() >= 2;
        // if cost is none then dual_bound_local_search returned no feasible solution, so we cannot search for a better one
        let temperature = match parameters.mode {
            LocalSearchMode::SimulatedAnnealing {
                T0,
                ..
            } => T0,
            LocalSearchMode::HillClimbing => 0.0,
        };
        let time_limit = parameters.parameters.time_limit.unwrap_or(f64::INFINITY);
        // Every transition the model can produce, used as the candidate pool for the
        // replace neighborhood. Computed once here since it never changes during search.
        let candidate_transitions: Vec<Transition> = model
            .forward_transitions
            .iter()
            .chain(model.forward_forced_transitions.iter())
            .cloned()
            .collect();
        // remaining time limit after dual_bound_local_search, if any, is passed to the local search
        let mut local_search = LocalSearch {
            model,
            base_cost_evaluator,
            root_cost,
            current_cost: cost.unwrap_or(root_cost),
            current: transitions.clone(),
            current_states: Vec::new(),
            current_costs: Vec::new(),
            best: Solution {
                cost,
                transitions,
                is_infeasible: cost.is_none(),
                time: initial_time,
                ..Default::default()
            },
            solvable,
            mode: parameters.mode,
            neighborhoods: parameters.neighborhoods,
            temperature,
            rng: Pcg64Mcg::seed_from_u64(parameters.seed),
            time_keeper: TimeKeeper::with_time_limit(time_limit),
            quiet: parameters.parameters.quiet,
            first_call: true,
            candidate_transitions,
        };

        if solvable {
            local_search.refresh_trace();
        }
        local_search.time_keeper.stop();

        local_search
    }

    // Recomputes the state and cost after every prefix of current
    // so we do not rollout the whole solution
    fn refresh_trace(&mut self) {
        let (states, costs) = get_trace(
            &self.model.target,
            self.root_cost,
            &self.current,
            &self.model,
        )
        .unzip();
        self.current_states = states;
        self.current_costs = costs;
    }

    fn generate_neighbor(&mut self) -> (Vec<Transition>, usize) {
        let n = self.current.len();
        let mut transitions = self.current.clone();

        // Two distinct indices in [0, n).
        let i = self.rng.random_range(0..n);
        let mut j = self.rng.random_range(0..n - 1);
        if j >= i {
            j += 1;
        } // j has to be different from i

        // Uniformly pick among whichever neighborhoods are enabled.
        let enabled: Vec<NeighborhoodKind> = [
            (self.neighborhoods.swap, NeighborhoodKind::Swap),
            (self.neighborhoods.relocate, NeighborhoodKind::Relocate),
            (self.neighborhoods.replace, NeighborhoodKind::Replace),
            (self.neighborhoods.twoopt, NeighborhoodKind::TwoOpt),
        ]
        .into_iter()
        .filter_map(|(enabled, kind)| enabled.then_some(kind))
        .collect();
        let kind = enabled[self.rng.random_range(0..enabled.len())];

        let prefix_len = match kind {
            NeighborhoodKind::Swap => {
                transitions.swap(i, j); // swap neighborhood
                i.min(j)
            }
            NeighborhoodKind::Relocate => {
                let transition = transitions.remove(i); // relocation neighborhood
                transitions.insert(j, transition);
                i.min(j)
            }
            NeighborhoodKind::Replace => {
                let replacement = self.candidate_transitions
                    [self.rng.random_range(0..self.candidate_transitions.len())]
                .clone();
                transitions[i] = replacement; // replace neighborhood
                i
            }
            NeighborhoodKind::TwoOpt => {
                let (i, j) = if i < j { (i, j) } else { (j, i) };
                transitions[i + 1..=j].reverse(); // 2-opt neighborhood
                i + 1
            }
        };

        (transitions, prefix_len)
    }

    // Best-improvement neighborhood exploration for hill climbing: evaluates every
    // swap and/or relocate move (O(n^2) neighbors) and returns the best feasible one.
    fn best_neighbor(&mut self) -> Option<(Vec<Transition>, usize, T)> {
        let n = self.current.len();
        let mut best: Option<(Vec<Transition>, usize, T)> = None;

        if self.neighborhoods.swap {
            let mut candidate = self.current.clone();

            for i in 0..n {
                for j in (i + 1)..n {
                    candidate.swap(i, j);

                    if let Some(cost) = self.evaluate(&candidate, i) {
                        if best
                            .as_ref()
                            .map_or(true, |&(_, _, best_cost)| self.is_better(cost, best_cost))
                        {
                            best = Some((candidate.clone(), i, cost));
                        }
                    }

                    candidate.swap(i, j); // undo the swap
                }
            }
        }

        if self.neighborhoods.relocate {
            let mut candidate = self.current.clone();

            for i in 0..n {
                for j in 0..n {
                    if i == j {
                        continue;
                    }

                    let transition = candidate.remove(i);
                    candidate.insert(j, transition);
                    let prefix_len = i.min(j);

                    if let Some(cost) = self.evaluate(&candidate, prefix_len) {
                        if best
                            .as_ref()
                            .map_or(true, |&(_, _, best_cost)| self.is_better(cost, best_cost))
                        {
                            best = Some((candidate.clone(), prefix_len, cost));
                        }
                    }

                    let transition = candidate.remove(j);
                    candidate.insert(i, transition); // undo the relocation
                }
            }
        }
        if self.neighborhoods.replace {
            let mut candidate = self.current.clone();

            let candidate_transitions = self.candidate_transitions.clone();

            for i in 0..n {
                for transition in &candidate_transitions {
                    let original_transition = candidate[i].clone();
                    candidate[i] = transition.clone();

                    if let Some(cost) = self.evaluate(&candidate, i) {
                        if best
                            .as_ref()
                            .map_or(true, |&(_, _, best_cost)| self.is_better(cost, best_cost))
                        {
                            best = Some((candidate.clone(), i, cost));
                        }
                    }

                    candidate[i] = original_transition; // undo the replacement
                }
            }
        }
        if self.neighborhoods.twoopt {
            let mut candidate = self.current.clone();

            for i in 0..n {
                // j = i + 1 would reverse a single-element slice (a no-op), so skip it.
                for j in (i + 2)..n {
                    candidate[i + 1..=j].reverse();

                    if let Some(cost) = self.evaluate(&candidate, i + 1) {
                        if best
                            .as_ref()
                            .map_or(true, |&(_, _, best_cost)| self.is_better(cost, best_cost))
                        {
                            best = Some((candidate.clone(), i + 1, cost));
                        }
                    }

                    candidate[i + 1..=j].reverse();
                }
            }
        }

        best
    }

    // Rollout from prefix to end & returns cost
    fn evaluate(&mut self, transitions: &[Transition], prefix_len: usize) -> Option<T> {
        let (state, cost) = if prefix_len == 0 {
            (self.model.target.clone(), self.root_cost)
        } else {
            (
                self.current_states[prefix_len - 1].clone(),
                self.current_costs[prefix_len - 1],
            )
        };
        let mut function_cache = ParentAndChildStateFunctionCache::new(&self.model.state_functions);
        let result = rollout(
            &state,
            &mut function_cache,
            cost,
            &transitions[prefix_len..],
            &mut self.base_cost_evaluator,
            &self.model,
        )?;

        result.is_base.then_some(result.cost)
    }

    // Decides whether a candidate with the given cost replaces `current`,
    // cooling down the temperature for simulated annealing along the way.
    fn accept(&mut self, cost: T) -> bool {
        if !exceed_bound(&self.model, cost, Some(self.current_cost)) {
            return true;
        }

        match self.mode {
            LocalSearchMode::HillClimbing => false,
            LocalSearchMode::SimulatedAnnealing { alpha, .. } => {
                let delta = if self.model.reduce_function == dypdl::ReduceFunction::Max {
                    self.current_cost - cost
                } else {
                    cost - self.current_cost
                }
                .to_continuous();
                let accept = self.rng.random::<f64>() < (-delta / self.temperature).exp();
                self.temperature *= alpha;

                accept
            }
        }
    }

    // Returns whether `cost` is a strict improvement over `other`.
    fn is_better(&self, cost: T, other: T) -> bool {
        !exceed_bound(&self.model, cost, Some(other))
    }
}

impl<T, B> Search<T> for LocalSearch<T, B>
where
    T: Numeric + Ord + Display,
    <T as str::FromStr>::Err: Debug,
    B: FnMut(T, T) -> T,
{
    fn search_next(&mut self) -> Result<(Solution<T>, bool), Box<dyn Error>> {
        if !self.solvable {
            return Ok((self.best.clone(), true));
        }

        if self.first_call {
            self.first_call = false;

            return Ok((self.best.clone(), false));
        }

        self.time_keeper.start();

        loop {
            if self.time_keeper.check_time_limit(self.quiet) {
                self.best.time = self.time_keeper.elapsed_time();
                self.best.time_out = true;
                self.time_keeper.stop();

                return Ok((self.best.clone(), true));
            }

            if matches!(self.mode, LocalSearchMode::HillClimbing) {
                if let Some((candidate, _, cost)) = self.best_neighbor() {
                    if self.accept(cost) {
                        self.current = candidate;
                        self.current_cost = cost;
                        self.refresh_trace();

                        if self.is_better(cost, self.best.cost.unwrap()) {
                            self.best.cost = Some(cost);
                            self.best.transitions = self.current.clone();
                            self.best.time = self.time_keeper.elapsed_time();

                            if !self.quiet {
                                print_primal_bound(&self.best);
                            }

                            self.time_keeper.stop();

                            return Ok((self.best.clone(), false));
                        }

                        continue;
                    }
                }

                // No neighbor improves on the current solution: local optimum reached.
                self.best.time = self.time_keeper.elapsed_time();
                self.time_keeper.stop();

                return Ok((self.best.clone(), true));
            }

            let (candidate, prefix_len) = self.generate_neighbor();
            let evaluated = self.evaluate(&candidate, prefix_len);

            let cost = match evaluated {
                Some(cost) => cost,
                None => continue, // infeasible neighbor: try another one
            };

            if self.accept(cost) {
                self.current = candidate;
                self.current_cost = cost;
                self.refresh_trace();

                if self.is_better(cost, self.best.cost.unwrap()) {
                    self.best.cost = Some(cost);
                    self.best.transitions = self.current.clone();
                    self.best.time = self.time_keeper.elapsed_time();

                    if !self.quiet {
                        print_primal_bound(&self.best);
                    }

                    self.time_keeper.stop();

                    return Ok((self.best.clone(), false));
                }
            }
        }
    }
}
